steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build container image'
    args: ['build', '-f', 'dockerfiles/backend.dockerfile', '-t', '${_IMAGE_TAG}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push container image'
    args: ['push', '${_IMAGE_TAG}']

substitutions:
  _IMAGE_TAG: 'europe-west1-docker.pkg.dev/mlops-group114/docker-images/backend:latest'