steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/mlops-group114/mlops-repo/train:latest', '-f', 'dockerfiles/train.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/mlops-group114/mlops-repo/train:latest']